import { Link } from 'react-router-dom';
import { ArrowRight, Sparkles } from 'lucide-react';
import './Hero.css';

const Hero = () => {
  const handleSmoothScroll = (e: React.MouseEvent<HTMLAnchorElement>, targetId: string) => {
    e.preventDefault();
    const element = document.getElementById(targetId);
    if (element) {
      const navbarHeight = 80;
      const elementPosition = element.getBoundingClientRect().top + window.pageYOffset;
      const offsetPosition = elementPosition - navbarHeight;

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth'
      });
    }
  };

  return (
    <section className="hero">
      <div className="hero-container">
        <div className="hero-content">
          <div className="hero-badge">
            <Sparkles size={16} />
            <span>Powered by Advanced AI</span>
          </div>
          
          <h1 className="hero-title">
            Turn Your eBooks Into
            <span className="gradient-text"> Studio-Quality Audiobooks</span>
            <br />— Instantly.
          </h1>
          
          <p className="hero-subtitle">
            Upload any EPUB/PDF and get chapter-wise narration generated by advanced AI voices.
            Professional audiobooks in minutes, not months.
          </p>
          
          <div className="hero-cta">
            <Link to="/register" className="cta-primary">
              Convert an eBook
              <ArrowRight size={20} />
            </Link>
            <a href="#pricing" className="cta-secondary" onClick={(e) => handleSmoothScroll(e, 'pricing')}>
              View Pricing
            </a>
          </div>
          
          <div className="hero-stats">
            <div className="stat">
              <div className="stat-number">10M+</div>
              <div className="stat-label">Books Converted</div>
            </div>
            <div className="stat">
              <div className="stat-number">50K+</div>
              <div className="stat-label">Happy Users</div>
            </div>
            <div className="stat">
              <div className="stat-number">99.9%</div>
              <div className="stat-label">Accuracy</div>
            </div>
          </div>
        </div>
        
        <div className="hero-visual">
          <div className="visual-container">
            {/* Book Input */}
            <div className="floating-card card-1">
              <div className="book-visual">
                <div className="book-cover">
                  <div className="book-spine"></div>
                  <div className="book-page"></div>
                  <div className="book-page page-2"></div>
                  <div className="book-text">📖</div>
                </div>
              </div>
              <div className="card-text">eBook</div>
              <div className="format-badges">
                <span className="format-badge">EPUB</span>
                <span className="format-badge">PDF</span>
              </div>
            </div>
            
            {/* Arrow 1 */}
            <div className="conversion-arrow arrow-1">
              <div className="arrow-line"></div>
              <div className="arrow-head">→</div>
              <div className="arrow-particles">
                <span className="particle"></span>
                <span className="particle"></span>
                <span className="particle"></span>
              </div>
            </div>
            
            {/* AI Processing */}
            {/* <div className="floating-card card-2">
              <div className="ai-processor">
                <div className="ai-core">
                  <Sparkles className="ai-icon" size={32} />
                </div>
                <div className="wave-animation">
                  <div className="wave"></div>
                  <div className="wave"></div>
                  <div className="wave"></div>
                  <div className="wave"></div>
                  <div className="wave"></div>
                </div>
              </div>
              <div className="card-text">AI Converting</div>
            </div> */}
            
            {/* Arrow 2 */}
            {/* <div className="conversion-arrow arrow-2">
              <div className="arrow-line"></div>
              <div className="arrow-head">→</div>
              <div className="arrow-particles">
                <span className="particle"></span>
                <span className="particle"></span>
                <span className="particle"></span>
              </div>
            </div> */}
            
            {/* Audio Output */}
            <div className="floating-card card-3">
              <div className="audio-visual">
                <div className="headphones">
                  <div className="headphone-band"></div>
                  <div className="headphone-cup left"></div>
                  <div className="headphone-cup right"></div>
                  <div className="sound-wave">
                    <span></span>
                    <span></span>
                    <span></span>
                  </div>
                </div>
              </div>
              <div className="card-text">Audiobook</div>
              <div className="format-badges">
                <span className="format-badge">MP3</span>
                <span className="format-badge">M4B</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
